CRA/Models/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using CarRental.Data;

namespace CarRental.MVC.Models
{


    public enum Roles { Manager, Employee, Customer };
  

    public class CustomerViewModel
    {
       

        public int ID { get; set; }

        [Required]
        [StringLength(30, MinimumLength = 2,ErrorMessage = "Firstname must contain at least 2 chatracters")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Lastname must contain at least 2 chatracters")]
        public string LastName { get; set; }


        [Required]
        [Display(Name = "User's Role")]
        [EnumDataType(typeof(Roles), ErrorMessage = "Please enter a valid Role of the user")]
        public Roles role { get; set; }

        [Display (Name = "Full Name")]
        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }          
        }

        [Required]
        [Display(Name = "Birth Data")]
        [RegularExpression(@"^(([0-2]\d|[3][0-1])\/([0]\d|[1][0-2])\/[2][0]\d{2})$|^(([0-2]\d|[3][0-1])\/([0]\d|[1][0-2])\/[2][0]\d{2}\s([0-1]\d|[2][0-3])\:[0-5]\d\:[0-5]\d)$", ErrorMessage = "Not A DateTime")]
        public DateTime? BirthData { get; set; }

        [Required]
        [Display(Name = "Gender")]
        [EnumDataType(typeof(Gender), ErrorMessage = "Please select a valid gender")]
        public Gender? gender { get; set; }





        [Required]
        [EmailAddress]       
        public string Email { get; set; }

        [Required]
        [StringLength(30, MinimumLength = 2,ErrorMessage = "Username must contain at least 6 chatracters")]        
        public string UserName { get; set; }

        [Required]
        [StringLength(30, MinimumLength = 6, ErrorMessage = "Password must contain  at least 6 characters")]
        public string Password { get; set; }


        public byte?[] Picture { get; set; }




       


        public   User toBaseClient_Details()
        {
            return new User
            {
                ID = ID,
                FirstName = FirstName,
                LastName = LastName,
                BirthData = BirthData,
                gender = gender.Value,
                Email = Email,
                UserName = UserName,
                Password = Password,
                Picture = Picture

            };
        }


        public CustomerViewModel() { }


        public CustomerViewModel(User domainClieentDetails)
        {
            

            this.ID = domainClieentDetails.ID;

            this.FirstName = domainClieentDetails.FirstName;

            this.LastName = domainClieentDetails.LastName;

            this.BirthData = domainClieentDetails.BirthData;

            this.UserName = domainClieentDetails.UserName;

            this.gender = domainClieentDetails.gender;

            this.Email = domainClieentDetails.Email;

            this.Password = domainClieentDetails.Password;

            this.Picture = domainClieentDetails.Picture;

        }

    }
}

CRA/Controllers/CustomerController.cs
using CarRental.BL;
using CarRental.Models;
using CarRental.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarRental.Controllers
{
    public class CustomerController : Controller
    {
        private readonly CustomerBL _customer;
        private static ModelView customerModel;
        private static CarViewModel customerCar;
        private  static double totallPrice;
        private static DateTime startDate;
        private static DateTime supposedReturn;
        private const string DEALS_IN_THE_BUSKET = "dealsinfo";
      

        public CustomerController() {
            _customer = new CustomerBL();         
        }


       
        [Authorize(Roles = "Employee, Manager, Customer")]
        [HttpPost]
        public ActionResult GetInfo(HelpModel hvm)
        {
            var date1 = hvm.StartDate.Split('-');
            var date2 = hvm.SupposedReturn.Split('-');
            startDate = new DateTime(int.Parse(date1[0]), int.Parse(date1[1]), int.Parse(date1[2]));
            supposedReturn = new DateTime(int.Parse(date2[0]), int.Parse(date2[1]), int.Parse(date2[2]));
            customerCar = new CarViewModel(_customer.GetCar(hvm.carID));
            customerModel = new ModelView(_customer.GetModel(hvm.modelID));
            totallPrice = hvm.totallPrice;
            return Json(JsonRequestBehavior.AllowGet);
        }




        [Authorize(Roles = "Employee, Manager, Customer")]
        public ActionResult Index()
        {
            var UserID = _customer.GetUserId(User.Identity.Name);
            ViewBag._Model = customerModel;
            ViewBag._Car = customerCar;
            ViewBag.price = totallPrice;
            ViewBag.userId = UserID; 
            ViewBag.startDate = startDate;
            ViewBag.supposedReturn = supposedReturn;
            var model = new DealViewModel();         
            return View(model);
        }

        [Authorize(Roles = "Employee, Manager, Customer")]
        [HttpPost]
        public ActionResult AddtoBusket(DealViewModel deal)
        {
            TempData["Success"] = "Reservation Succeded!";
            var deals = Session[DEALS_IN_THE_BUSKET] as List<DealViewModel>;

            if (deals == null) {

                deals = new List<DealViewModel>();
            }

            deals.Add(deal);
            Session[DEALS_IN_THE_BUSKET] = deals;
            return  RedirectToAction("MyBusket");
        }



        [Authorize(Roles = "Employee, Manager, Customer")]
        public ActionResult MyBusket()
        {
            var deals = Session[DEALS_IN_THE_BUSKET] as List<DealViewModel>;                   
            return View(deals);
        }


        [Authorize(Roles = "Employee, Manager, Customer")]
        public ActionResult PreviousReservations()
        {
            var UserID = _customer.GetUserId(User.Identity.Name);
            var myDeals = _customer.GetPreviousDeals(UserID).Select(d => new DealViewModel(d));
            return View(myDeals);
        }

        public ActionResult Confimation(int dealID)
        {
            var deals = Session[DEALS_IN_THE_BUSKET] as List<DealViewModel>;
            var currenDeal = deals.Where(d => d.ID == dealID).FirstOrDefault();
            deals.Remove(currenDeal);
            Session[DEALS_IN_THE_BUSKET] = deals;
           _customer.ConfirmDeal(currenDeal.toBaseDateDetails());
            TempData["Success"] = "Reservation Completed!";

            return RedirectToAction("PreviousReservations");
        }

        public ActionResult RemoveItemFromBusket(int dealID)
        {
            var deals = Session[DEALS_IN_THE_BUSKET] as List<DealViewModel>;
            var dealtoRemove = deals.Where(d => d.ID == dealID).FirstOrDefault();
            deals.Remove(dealtoRemove);
            Session[DEALS_IN_THE_BUSKET] = deals;
            TempData["Success"] = "Order Removed! ";

            return RedirectToAction("MyBusket");
        }

        public ActionResult ClearBusket()
        {
            Session[DEALS_IN_THE_BUSKET] = new List<DealViewModel>();
            return RedirectToAction("MyBusket");
        }

        public ActionResult QuantityOfItemsInBusket()
        {
            int count;
            var deals = Session[DEALS_IN_THE_BUSKET] as List<DealViewModel>;
            if(deals == null)
            {
                count = 0;
            }
            else
            {
                count = deals.Count;
            }
           return Json(count,JsonRequestBehavior.AllowGet);
        }
    }
}

CRA/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarRental.BL;
using CarRental.Dal;
using CarRental.Data;
using CarRental.Models;
using CarRental.MVC.Models;
using CRA.BL;

namespace CarRental.Controllers {
    public class GuestController : Controller {
        private readonly ManagerBL manager;
        private readonly GuestBL guest;
        private static IEnumerable<ModelView> allmodels;
        private static IEnumerable<ManufactorerViewModel> allManufacturers;
        private static IEnumerable<Car> domaninCars;
        private static IEnumerable<CarViewModel> allCars;
        private static IEnumerable<DealViewModel> allDeals;

        public GuestController () {
            manager = new ManagerBL ();
            guest = new GuestBL ();
        }

        public ActionResult Index () {
            domaninCars = guest.GetAllCarsinProperState ();
            allCars = domaninCars.Select (c => new CarViewModel (c));
            allmodels = guest.GettAllModels ().Select (c => new ModelView (c));
            allManufacturers = guest.GettAllManufacturers ().Select (c => new ManufactorerViewModel (c));
            allDeals = manager.GetAllDeals ().Select (d => new DealViewModel (d));
            List<SelectListItem> modelsItems = new List<SelectListItem> ();
            List<SelectListItem> manufacturersItems = new List<SelectListItem> ();

            foreach (var model in allmodels) {
                modelsItems.Add (new SelectListItem { Text = model.NameofModel, Value = model.ID.ToString () });
            }

            foreach (var man in allManufacturers) {
                manufacturersItems.Add (new SelectListItem { Text = man.manufacturerName, Value = man.ID.ToString () });
            }

            ViewBag.model = modelsItems;
            ViewBag.manufac = manufacturersItems;
            return View (domaninCars);
        }

        public ActionResult HelpAjax () {
            var helper = new HelpModel ();
            helper.AllManufacturers = allManufacturers;
            helper.AllCarModels = allmodels;
            helper.AllDeals = allDeals;
            helper.AllCars = allCars;
            return Json (helper, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetImage (int id) {
            var image = guest.GetImage (id);
            return File (image, "image/jpeg");
        }

        public ActionResult PriceCalculation (int? carid) {
            var car = (from c in domaninCars where c.CarID == carid.Value select c).FirstOrDefault ();

            return View (car);
        }
    }
}

CRA/Views/Customer/Index.cshtml
@using CarRental.MVC.Models
@model DealViewModel


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_layout.cshtml";

    var linktopicture = "/Guest/GetImage/" + @ViewBag._Model.ID.ToString();

    

    Model.CarID = ViewBag._car.ID;

    Model.ClientID = ViewBag.userId;

    Model.StartDate = ViewBag.startDate.ToShortDateString();

    Model.SupposedReturn = ViewBag.supposedReturn.ToShortDateString();

}

<h3  >       Your Selection</h3>

<div class="reservation">

    <h2>@ViewBag._Model.NameofModel</h2>
    <br />
    <br />
    <img src="@linktopicture" />
    <br />
    <br />
    <p>Price: @ViewBag.price $</p>
    
    @using (Html.BeginForm("AddtoBusket", "Customer", FormMethod.Post))
    {
    
    <br />
    @Html.LabelFor(d => d.StartDate, "Day of pick up:")
    @Html.DisplayFor(d => d.StartDate)
    <br />
    @Html.LabelFor(d => d.SupposedReturn, "Return Date:")
    @Html.DisplayFor(d => d.SupposedReturn)
        <br />
    @Html.HiddenFor(x => x.CarID);
     @Html.HiddenFor(x => x.ClientID);
     @Html.HiddenFor(x => x.StartDate);
     @Html.HiddenFor(x => x.SupposedReturn);
    <br />
    <input type="submit"  value="Add to Busket" class="btn btn-success" /> <a class="btn btn-danger" href="@Url.Action("Index", "Guest")">Cancell</a>  
    }
    <br />
    <br />
</div>



   
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<script src="~/Scripts/ScriptLibriaries/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/ScriptLibriaries/jquery-ui-1.12.1.min.js"></script>
<script src="~/Scripts/ScriptLibriaries/bootstrap.min.js"></script>
<script src="~/Scripts/ScriptLibriaries/moment.min.js"> </script>
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
<script src="~/Scripts/ViewScripts/MainScript.js"></script>

CRA/Views/Customer/MyBusket.cshtml
@model IEnumerable<CarRental.MVC.Models.DealViewModel>
@{
    ViewBag.Title = "MyBusket";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<h2>MyBusket</h2>

@if (TempData["Success"] != null)
{
    <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
}


<div class="container-fluid">
    <div class="row">
        <div class="col-sm-5">
            <table class="table table-bordered table-hover table-condensed">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.StartDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SupposedReturn)
                    </th>
                   
                    <th>
                        @Html.DisplayNameFor(model => model.ClientID)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CarID)
                    </th>
                    <th></th>

                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SupposedReturn)
                        </td>
                        
                        <td>
                            @Html.DisplayFor(modelItem => item.ClientID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CarID)
                        </td>
                        <td>
                            <a class="btn btn-success" href="@Url.Action("Confimation", new { dealID = item.ID })">Confirm</a>  <a class="btn btn-primary" href="@Url.Action("Index","Guest")">Continue Shopping</a>   <a class="btn btn-danger" href="@Url.Action("RemoveItemFromBusket", new { dealID = item.ID })">Delete</a> 
                        </td>
                        
                    </tr>

                    
                }

            </table>
            <a class="btn btn-danger" href="@Url.Action("ClearBusket")">Clear Busket</a>
        </div>
    </div>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<script src="~/Scripts/ScriptLibriaries/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/ViewScripts/MainScript.js"></script>

CRA/Views/Customer/PreviousReservations.cshtml
@model IEnumerable<CarRental.MVC.Models.DealViewModel>

@{
    ViewBag.Title = "PreviousReservations";
    Layout = "~/Views/Shared/_layout.cshtml";
}


<h3>Your Previous Reservations</h3>


@if (TempData["Success"] != null)
{
    <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
}


<div class="container-fluid">
    <div class="row">
        <div class="col-sm-5">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.StartDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SupposedReturn)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.RealReturn)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ClientID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CarID)
                        </th>

                    </tr>
                </thead>


                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.StartDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SupposedReturn)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.RealReturn)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ClientID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CarID)
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
            </div>
        </div>
    </div>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
<br />
<br />
<br />
<br />
<br />
<br />
<script src="~/Scripts/ScriptLibriaries/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/ScriptLibriaries/jquery-ui-1.12.1.min.js"></script>
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
<script src="~/Scripts/ViewScripts/MainScript.js"></script>
<script>

    $(function () {

        $('table').DataTable();

    });


</script>